MEASURE = 'm'
BEAT = 'b'
HALFBEAT = 'h'

FILENAME_SUFFIX_COMBINED = 'combined'
FILENAME_SUFFIX_NO_LYRICS = 'leadsheet'
FILENAME_SUFFIX_LYRICS_ONLY = 'lyrics'

HTML_OUTPUT_SUBDIR = 'html'
PDF_OUTPUT_SUBDIR = 'pdf'
